name: dart_obs_ws
description: Dart library for obs-websocket
version: 1.0.0

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  crypto: 3.0.2 # Generating hash for password
  uuid: 3.0.6 # Generating request IDs
  web_socket_channel: 2.2.0 # Cross-platform WebSocket support

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
