name: dart_obs_ws
description: Dart library for obs-websocket
version: 1.0.0

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
