name: obs_ws
description: Dart library to remotely control OBS Studio over the obs-websocket plugin (v5.0.0+) protocol
version: 1.0.0
homepage: https://github.com/entriphy/dart_obs_ws
repository: https://github.com/entriphy/dart_obs_ws

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  crypto: ^3.0.0 # Generating hash for password
  web_socket_channel: ^3.0.1 # Cross-platform WebSocket support

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
